language: python
sudo: false
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install nose
branches:
  only:
  - master
script: nosetests
addons:
  ssh_known_hosts: 138.68.59.141
after_success:
- ssh chun@138.68.59.141 /home/chun/scripts/test.sh
before_install:
- openssl aes-256-cbc -K $encrypted_db7d4a61814d_key -iv $encrypted_db7d4a61814d_iv
  -in id_rsa.enc -out id_rsa -d
